name: Publish Nuget Package
on: workflow_dispatch
jobs:  
  publish:    
    runs-on: windows-latest
    permissions:
      packages: write
    steps:      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Packages
        working-directory: ./SimplSharp
        run: nuget restore

      - name: Build Solution
        working-directory: ./SimplSharp
        run: msbuild.exe SimplSharpTools.sln /p:platform="Any CPU" /p:configuration="Release"

      - name: Create NuGet Package
        working-directory: ./SimplSharp
        run: nuget pack

      - name: List workspace contents
        working-directory: ./SimplSharp
        run: ls

      - name: Authenticate to GitHub Packages
        working-directory: ./SimplSharp
        run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/fasteddy516/index.json" -UserName fasteddy516 -Password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText 

      - name: Publish to GitHub Packages
        working-directory: ./SimplSharp
        run: nuget push "*.nupkg" -Source "GitHub"
        
